server:
      port: 9000

datasource :
    db :
        username : devadm
        password : Dev@gianty123
        databaseUrl : jdbc:mysql://192.168.30.208:3306/flyway_demo?useSSL=false&characterEncoding=UTF-8
        databaseDriver : com.mysql.jdbc.Driver
